### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Minesraft2** [Minesraft-Is-Best/Blooket-Mod-menu#1]
The two scripts in this repo are stolen directly from mine, please remove them.

**Comment by Minesraft-Is-Best** [comment]
I recreated it

**Comment by Minesraft-Is-Best** [comment]
thats all i did

**Comment by Minesraft-Is-Best** [comment]
your my inspiration

**Comment by Minesraft-Is-Best** [comment]
Time to close this

**Comment by Minesraft2** [comment]
Recreating is against the license, take it down by 4pm cst or I'll submit a dmca

**Comment by Minesraft2** [comment]
I'll submit the dmca now.

**Comment by VillainsRule4000** [comment]
@Minesraft2 wasn't privated

**Comment by orangemonkey01** [comment]
its still public

**Comment by orangemonkey01** [comment]
bruh
